---
title: "Conceptual Questions"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

Answers go here!

-   If your working directory is myfolder/homework/, what relative path would you specify to get the file located at myfolder/MyData.csv?

> The relative path I would specify to get MyData.csv is read.csv("myfolder/MyData.csv")

-   What are the major benefits of using R projects?

> The major benefits of using R projects is that they provide an intuitive way to separate work into different organized groups. Within each group is its own working directory, folder structure, etc. It also simplifies the sharing of R code to others for contributions.

-   What is git and what is github?

> Git is a system of version control that tracks changes to programs/code. Github is a website that hosts Git repositories

-   What are the two main differences between a tibble and a data.frame?

> The tibble is a reimagining of the data frame. The two main differences is that a tibble does less and is more temperamental, meaning that working with them tends to encourage more expressive code. 

-   Rewrite the following nested function call using BaseR’s chaining operator:
arrange(filter(select(as_tibble(iris), starts_with("Petal"), Species), Petal.Length < 1.55), Species)

> as_tibble(iris) |>
  select(starts_with("Petal"), Species) |>
  filter(Petal.Length < 1.55) |>
  arrange(Species)
  
> as a chunk:

```{r}
as_tibble(iris) |>
  select(starts_with("Petal"), Species) |>
  filter(Petal.Length < 1.55) |>
  arrange(Species)
```